# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure('2') do |config|
  config.vm.box = 'almalinux/9'

  config.vm.provider 'libvirt' do |vb|
    vb.memory = 1024 * 2
    vb.cpus = 2
    vb.video_type = 'virtio'
  end

  config.vm.synced_folder '.', '/vagrant', disabled: true

  # Server
  config.vm.define 'server1' do |server|
    server.vm.hostname = 'server1.local'
    server.vm.network 'private_network', ip: '172.17.64.100'
    server.vm.provision 'shell', inline: <<~SHELL1
      echo server1
      sudo dnf -y install telnet nc

      sudo cat <<'LHN' | sudo tee /etc/mail/local-host-names
server1
LHN

      sudo m4 /etc/mail/sendmail.mc > /etc/mail/sendmail.cf
      sudo systemctl restart sendmail

      sleep 60

      sudo dnf install -y epel-release
      sudo dnf install -y swaks

      # HELO - PLAIN
      swaks --to vagrant@server1 \
            --from vagrant@server1 \
            --server server2 \
            --port 587 \
            --auth LOGIN \
            --auth-user vagrant \
            --auth-password vagrant \
            --tls \
            --helo server1

      # EHLO - STARTTLS
      swaks --to vagrant@server1 \
            --from vagrant@server1 \
            --server server2 \
            --port 587 \
            --auth LOGIN \
            --auth-user vagrant \
            --auth-password vagrant \
            --tls \
            --helo server1

      echo; echo; echo;
      sleep 5

      {
       echo "HELO server1"
       echo "MAIL FROM:<vagrant@server1>"
        echo "RCPT TO:<vagrant@server1>"
        echo "DATA"
        echo "Subject: this is a testmail ABC"
        echo ""
        echo "this is a testmail EFG"
        echo "."
        echo "QUIT"
      } | nc server2 25
      
      sleep 60
      echo
      echo "####### /var/spool #######"
      sudo cat /var/spool/mail/vagrant

      echo
      echo "####### MAILDIR #######"
      sudo cat /home/vagrant/Maildir/*


      echo
      echo "####### MAILDIR #######"
      {
        echo USER vagrant
        echo PASS vagrant
        echo LIST
        echo RETR 1
        echo RETR 2
        echo RETR 3
        echo QUIT
      } | nc localhost 110
    SHELL1
  end

  # Server
  config.vm.define 'server2' do |server|
    server.vm.hostname = 'server2.local'
    server.vm.network 'private_network', ip: '172.17.64.101'
    server.vm.provision 'shell', inline: <<~SHELL2
      echo server2

      # no need db generating by hand
      cat <<'EOF' | sudo tee -a /etc/mail/access
Connect:server1.local    RELAY
EOF
      cat <<'EOF' | sudo tee /etc/mail/mailertable               
server1    esmtp:[172.17.64.100]
EOF

      sudo m4 /etc/mail/sendmail.mc > /etc/mail/sendmail.cf
      sudo systemctl restart sendmail
    SHELL2
  end

  config.vm.provision 'shell', inline: <<~SHELLC
    sudo dnf -y install firewalld
    sudo systemctl start firewalld
    sudo firewall-cmd --permanent --zone=public --add-port=25/tcp
    sudo firewall-cmd --permanent --zone=public --add-port=587/tcp
    sudo firewall-cmd --reload
    sudo systemctl restart firewalld

    (echo vagrant; echo vagrant) | sudo passwd vagrant

    sudo dnf -y install sendmail m4 sendmail-cf

    cat <<'ETCHOSTS' | tee -a /etc/hosts

172.17.64.100 server1.local server1
172.17.64.101 server2.local server2
ETCHOSTS

    sudo sed -i 's@^DAEMON_OPTIONS(@dnl DAEMON_OPTIONS(@g' /etc/mail/sendmail.mc

    cat <<'PROCMAILEOF' | sudo tee /etc/procmailrc
MAILDIR=$HOME/Maildir/
DEFAULT=$MAILDIR
LOGFILE=$HOME/procmail.log
VERBOSE=on
PROCMAILEOF

    install -o vagrant -g vagrant -m 0755 -d /home/vagrant/Maildir

    # DOVECOT
    sudo yum install -y dovecot
    sed -i 's/^#protocols/protocols/g' /etc/dovecot/dovecot.conf
    sed -i 's@^#   mail_location = maildir@   mail_location = maildir@g' /etc/dovecot/conf.d/10-mail.conf

    sed -i 's@auth_mechanisms = plain@auth_mechanisms = plain login@g' /etc/dovecot/conf.d/10-auth.conf

    #sed -i 's@^ssl = required@ssl = no@g' /etc/dovecot/conf.d/10-ssl.conf
    sed -i 's@^ssl = required@ssl = yes@g' /etc/dovecot/conf.d/10-ssl.conf

    sed -i 's@^    #port = 587@    port = 587@g' /etc/dovecot/conf.d/10-master.conf

    sed -i 's@^}@#}@g' /etc/dovecot/conf.d/20-submission.conf 
    cat <<'SUBM' >> /etc/dovecot/conf.d/20-submission.conf 
  submission_relay_host = 127.0.0.1
  submission_relay_port = 25
  submission_relay_trusted = yes
}
submission_relay_host = 127.0.0.1
submission_relay_port = 25
SUBM


    systemctl restart dovecot

  SHELLC
end
