# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure('2') do |config|
  config.vm.box = 'almalinux/9'

  config.vm.provider 'libvirt' do |vb|
    vb.memory = 1024 * 2
    vb.cpus = 2
    vb.video_type = 'virtio'
  end

  config.vm.synced_folder '.', '/vagrant', disabled: true

  # Server
  config.vm.define 'server1' do |server|
    server.vm.hostname = 'server1.local'
    server.vm.network 'private_network', ip: '172.17.64.100'
    server.vm.provision 'shell', inline: <<~SHELL1
      echo server1
      sudo dnf -y install telnet nc

      sudo cat <<'LHN' | sudo tee /etc/mail/local-host-names
server1
LHN

      sudo m4 /etc/mail/sendmail.mc > /etc/mail/sendmail.cf
      sudo systemctl restart sendmail

      sleep 15

      {
        echo "HELO server1"
        echo "MAIL FROM:<vagrant@server2>"
        echo "RCPT TO:<vagrant@server1>"
        echo "DATA"
        echo "Subject: this is a testmail ABC"
        echo ""
        echo "this is a testmail EFG"
        echo "."
        echo "QUIT"
      } | nc server2 25
      
      sleep 5
      echo
      echo "####### /var/spool #######"
      sudo cat /var/spool/mail/vagrant

      echo "####### MAILDIR #######"
      sudo cat /home/vagrant/Maildir/*
    SHELL1
  end

  # Server
  config.vm.define 'server2' do |server|
    server.vm.hostname = 'server2.local'
    server.vm.network 'private_network', ip: '172.17.64.101'
    server.vm.provision 'shell', inline: <<~SHELL2
      echo server2

      # no need db generating by hand
      cat <<'EOF' | sudo tee -a /etc/mail/access
Connect:server1.local    RELAY
EOF
      # ?
      cat <<'EOF' | sudo tee /etc/mail/mailertable               
server1    esmtp:[172.17.64.100]
EOF

      sudo m4 /etc/mail/sendmail.mc > /etc/mail/sendmail.cf
      sudo systemctl restart sendmail
    SHELL2
  end

  config.vm.provision 'shell', inline: <<~SHELLC
    sudo systemctl stop firewalld || true
    sudo dnf -y install sendmail m4 sendmail-cf

    cat <<'ETCHOSTS' | tee -a /etc/hosts

172.17.64.100 server1.local server1
172.17.64.101 server2.local server2
ETCHOSTS

    sudo sed -i 's@^DAEMON_OPTIONS(@dnl DAEMON_OPTIONS(@g' /etc/mail/sendmail.mc


    cat <<'PROCMAILEOF' | tee /etc/procmailrc
MAILDIR=$HOME/Maildir
DEFAULT=$MAILDIR
LOGFILE=$HOME/procmail.log
VERBOSE=on
PROCMAILEOF
    install -o vagrant -g vagrant -m 0755 -d /home/vagrant/Maildir

    # DOVECOT
    sudo yum install -y dovecot
sed -i 's/^#protocols/protocols/g' /etc/dovecot/dovecot.conf
systemctl restart dovecot

  SHELLC
end
